#!/bin/bash
# WIP Automate some of the annoying parts


sdcard_backup_path=''
pc_backup_path=''
mtp_path='/run/user/1000/gvfs/mtp\:host\=%5Busb%3A001%2C027%5D/'


for dir in /run/user/1000/gvfs/mtp*; do
    test -d "$dir" || echo 'MTP path not found!'; exit 1
    mtp_path=$dir
    break 1
done

ls $mtp_path

